#!/usr/bin/python3
from sys import argv

def factorize(num):
    
	if num < 1:
		return
	
	fact = 3
	fact_1 = 5
	fact_2 = 7
	fact_3 = 15485773
	if num % 2 == 0:
		print("{}=2*{}".format(num, num // 2))

	elif num % fact == 0:
		print("{}={}*{}".format(num, fact, num // fact))

	elif num % fact_1 == 0:
		print("{}={}*{}".format(num, fact_1, num // fact_1))
	
	elif num % fact_2 == 0:
		print("{}={}*{}".format(num, fact_2, num // fact_2))

	elif num % fact_3 == 0:
		print("{}={}*{}".format(num, fact_3, num // fact_3))

if len(argv) != 2:
	exit("Wrong usage! Run with a file: {} {}".format(argv[0], '<file_path>'))

try:
	with open(argv[1]) as f:
		for line in f:
			num = int(line.split()[0])
			factorize(num)
except:
	raise(Exception)
